### ISSUE TITLE
Have you tried tensorflow serving?

### ISSUE THREAD

**Issue by pharrellyhy** [idealo/falcon-prediction-app#1]
Hi,

We are trying to serve our model using tf serving. Is it ok to use Falcon + Gunicorn + Gevent + tf serving? Currently we might only need to handle 500 requests/s. So maybe Nginx is not necessary? Thanks.

**Comment by pharrellyhy** [comment]
If not using tf serving, how the model handle multiple request simultaneously?

**Comment by datitran** [comment]
To handle multiple request on our side, we use Kubernetes. We can scale up containers very fast if we need it. There is also autoscaling. But yes you can use tf serving, however you make yourself restrictive to Tensorflow only. I rather have a solution where I can plug in/out models from different machine learning frameworks.

**Comment by pharrellyhy** [comment]
@datitran Thanks for your reply. I'm not familiar with large scale deployment. Can I ask which part will handle multiple requests, the model itself or other part, like you said, the Kubernetes?

**Comment by datitran** [comment]
Kubernetes will handle this. You will scale containers, called pods and then this will able to handle multiple requests.

**Comment by naveenmarthala** [comment]
is it not possible to achieve similar level of dynamically scaling up and down to serving millions of requests/sec to dozens of millions/sec, without using Kubernetes. If yes, why are the reasons you are using Kubernetes, if I can ask. 

Asking this because, I am learning things just like OP is; and also because I have heard many bad things about Kubernetes failing in production(https://k8s.af/).

Thanks.
